# Generated by Django 3.1 on 2020-08-27 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlModel',
            fields=[
                ('short_url_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('long_url', models.URLField()),
                ('expiration_datetime', models.DateTimeField()),
                ('access_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vilantis_short_urls',
            },
        ),
    ]
