# Generated by Django 3.1 on 2020-08-27 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 18, 5, 40, 268521)),
        ),
    ]
