# Generated by Django 3.1 on 2020-08-27 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200827_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 18, 22, 45, 601286)),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_url_id',
            field=models.CharField(default='1678c101', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
