# Generated by Django 3.1 on 2020-08-27 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200827_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturlmodel',
            name='access_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='access_limit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 18, 44, 40, 970650)),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_url_id',
            field=models.CharField(default='46f0b88c', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
