# Generated by Django 3.1 on 2020-08-28 14:17

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickStatisticModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('http_referer', models.URLField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'short url statistic',
                'db_table': 'vilantis_short_url_click_statistics',
            },
        ),
        migrations.CreateModel(
            name='ShortURLModel',
            fields=[
                ('short_url_id', models.CharField(default=backend.models.ShortURLModel.generate_short_url_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('expiration_datetime', models.DateTimeField(default=backend.models.ShortURLModel.generate_expiration_datetime)),
                ('long_url', models.URLField()),
                ('access_limit', models.PositiveSmallIntegerField(default=100)),
                ('access_counter', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'short url',
                'db_table': 'vilantis_short_urls',
            },
        ),
        migrations.AddIndex(
            model_name='shorturlmodel',
            index=models.Index(fields=['short_url_id'], name='vilantis_sh_short_u_7e003a_idx'),
        ),
        migrations.AddField(
            model_name='clickstatisticmodel',
            name='short_url',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='backend.shorturlmodel'),
        ),
        migrations.AddIndex(
            model_name='clickstatisticmodel',
            index=models.Index(fields=['short_url'], name='vilantis_sh_short_u_86a83a_idx'),
        ),
    ]
