# Generated by Django 3.1 on 2020-09-02 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='long_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
